# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
        # Install dependencies
      - name: Install dependencies
        run: npm install
       
      # Build app for production
      - name: Build Angular app
        run: npm run build:prod
      - name: List dist folder
        run: ls -R dist

      # Route file renaming
      - name: rename index for routing
        run: mv dist/heroes-app/browser/index.html dist/heroes-app/browser/404.html
        # Deploy to github pages
      - name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
